extensions: {}
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-stable-13.09
module-template: ! 'module MODULE_NAME where

'
ghc-args:
- -Wall
modules:
  Control.IsoTraversable:
    filename: src/Control/IsoTraversable.hs
