extensions: {}
cabal-file: project.cabal
version: 1
environment: ghc-7.4.2-stable-13.09
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Main(src/Main.hs):
    filename: src/Main.hs
